language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "yingw-github"

jdk:
  - oraclejdk8
  - openjdk8

script:
  - mvn clean test sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
